In [ ]:
import yfinance as yf

ticker = 'googl'
stock = yf.Ticker(ticker)
earning_df = stock.get_earnings_dates(limit=100)
type(earning_df)

pandas.core.frame.DataFrame

In [ ]:
earning_df.head()

EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2024-10-22 16:00:00-04:00           NaN           NaN          NaN
2024-07-23 16:00:00-04:00           NaN           NaN          NaN
2024-04-23 16:00:00-04:00           NaN           NaN          NaN
2024-01-31 16:00:00-05:00          1.59           NaN          NaN
2023-10-24 12:00:00-04:00          1.45          1.55       0.0682

In [ ]:
earning_df.to_csv('earning.csv', index=False)

In [ ]:
import pandas as pd

earning_df_from_csv = pd.read_csv('earning.csv')
earning_df_from_csv.head()

EPS Estimate  Reported EPS  Surprise(%)
0           NaN           NaN          NaN
1           NaN           NaN          NaN
2           NaN           NaN          NaN
3          1.59           NaN          NaN
4          1.45          1.55       0.0682

In [ ]:
earning_array = earning_df.values
earning_array[:2]

array([[nan, nan, nan],
       [nan, nan, nan]])

In [ ]:
earning_df_from_array = pd.DataFrame(data=earning_array, columns=earning_df.columns.values)
earning_df_from_array.head()

EPS Estimate  Reported EPS  Surprise(%)
0           NaN           NaN          NaN
1           NaN           NaN          NaN
2           NaN           NaN          NaN
3          1.59           NaN          NaN
4          1.45          1.55       0.0682

In [ ]:
earning_df.columns.values # 데이터 프레임 열 이름

array(['EPS Estimate', 'Reported EPS', 'Surprise(%)'], dtype=object)

In [ ]:
# 데이터 프레임 열 선택
earning_col = earning_df[['EPS Estimate']].head()
earning_col.head()

EPS Estimate
Earnings Date                          
2024-10-22 16:00:00-04:00           NaN
2024-07-23 16:00:00-04:00           NaN
2024-04-23 16:00:00-04:00           NaN
2024-01-31 16:00:00-05:00          1.59
2023-10-24 12:00:00-04:00          1.45

In [ ]:
type(earning_col) # 데이터 프레임: 2차원 배열

pandas.core.frame.DataFrame

In [ ]:
earning_col = earning_df['EPS Estimate']
earning_col.head()

Earnings Date
2024-10-22 16:00:00-04:00     NaN
2024-07-23 16:00:00-04:00     NaN
2024-04-23 16:00:00-04:00     NaN
2024-01-31 16:00:00-05:00    1.59
2023-10-24 12:00:00-04:00    1.45
Name: EPS Estimate, dtype: float64

In [ ]:
type(earning_col) # Series: 1차원 배열

pandas.core.series.Series

In [ ]:
# 데이터 프레임 행 선택
earning_df[1:3]

EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2024-07-23 16:00:00-04:00           NaN           NaN          NaN
2024-04-23 16:00:00-04:00           NaN           NaN          NaN

In [ ]:
earning_df_new_index = pd.DataFrame(
    data=earning_array,
    columns=earning_df.columns.values,
    index=range(1, len(earning_df)+1))
earning_df_new_index.head()

EPS Estimate  Reported EPS  Surprise(%)
1           NaN           NaN          NaN
2           NaN           NaN          NaN
3           NaN           NaN          NaN
4          1.59           NaN          NaN
5          1.45          1.55       0.0682

In [ ]:
# earning_df_new_index[1:3]
earning_df_new_index.iloc[1:3] # 인덱스 위치/implicit(암묵적) location

EPS Estimate  Reported EPS  Surprise(%)
2           NaN           NaN          NaN
3           NaN           NaN          NaN

In [ ]:
earning_df_new_index.loc[1:3] # 인덱스 명/명시적

EPS Estimate  Reported EPS  Surprise(%)
1           NaN           NaN          NaN
2           NaN           NaN          NaN
3           NaN           NaN          NaN

In [ ]:
earning_df_new_index.iloc[1:4,[0,2]]

EPS Estimate  Surprise(%)
2           NaN          NaN
3           NaN          NaN
4          1.59          NaN

In [ ]:
earning_df_new_index.loc[1:3, ['EPS Estimate']]

EPS Estimate
1           NaN
2           NaN
3           NaN

In [ ]:
earning_df[earning_df['EPS Estimate'] > 1]

EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2024-01-31 16:00:00-05:00          1.59           NaN          NaN
2023-10-24 12:00:00-04:00          1.45          1.55       0.0682
2023-07-25 12:00:00-04:00          1.34          1.44       0.0754
2023-04-25 12:00:00-04:00          1.07          1.17       0.0972
2023-02-02 11:00:00-05:00          1.18          1.05      -0.1073
2022-10-25 12:00:00-04:00          1.25          1.06      -0.1514
2022-07-26 12:00:00-04:00          1.28          1.21      -0.0541
2022-04-26 12:00:00-04:00          1.30          1.23      -0.0500
2022-02-01 11:00:00-05:00          1.37          1.53       0.1224
2021-10-26 12:00:00-04:00          1.17          1.40       0.1921

In [ ]:
earning_df[(earning_df['EPS Estimate'] > 1) & (earning_df['Surprise(%)'] > 0)]

EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2023-10-24 12:00:00-04:00          1.45          1.55       0.0682
2023-07-25 12:00:00-04:00          1.34          1.44       0.0754
2023-04-25 12:00:00-04:00          1.07          1.17       0.0972
2022-02-01 11:00:00-05:00          1.37          1.53       0.1224
2021-10-26 12:00:00-04:00          1.17          1.40       0.1921

In [ ]:
import numpy as np

# 조건에 맞는 인덱스 추출
index = np.where((earning_df['EPS Estimate'] > 1) &
                 (earning_df['Surprise(%)'] > 0))
index

(array([ 4,  5,  6, 11, 12]),)

In [ ]:
# 랜덤 샘플 추출
len(earning_df.sample(n=5))

5

In [ ]:
len(earning_df.sample(frac=0.5)), len(earning_df) # frac: 0~1, 전체 수의 비율만큼 랜덤 추출

(40, 81)

In [ ]:
# 누락 데이터(NaN) 처리
# 1.
earning_fillna = earning_df.fillna({'EPS Estimate': 1})
earning_fillna.head()

EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2024-10-22 16:00:00-04:00          1.00           NaN          NaN
2024-07-23 16:00:00-04:00          1.00           NaN          NaN
2024-04-23 16:00:00-04:00          1.00           NaN          NaN
2024-01-31 16:00:00-05:00          1.59           NaN          NaN
2023-10-24 12:00:00-04:00          1.45          1.55       0.0682

In [ ]:
# ?earning_df.fillna
earning_df.fillna?

In [ ]:
# 2.
earning_sample = earning_df.dropna()
len(earning_sample), len(earning_df)

(77, 81)

In [ ]:
earning_sample.head()

EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2023-10-24 12:00:00-04:00          1.45          1.55       0.0682
2023-07-25 12:00:00-04:00          1.34          1.44       0.0754
2023-04-25 12:00:00-04:00          1.07          1.17       0.0972
2023-02-02 11:00:00-05:00          1.18          1.05      -0.1073
2022-10-25 12:00:00-04:00          1.25          1.06      -0.1514

In [ ]:
# 0부터 순차적으로 index 재설정
# earning_sample = earning_sample.reset_index(drop=False) # 기존 index값이 열로 생성됨.
earning_sample = earning_sample.reset_index(drop=True)
earning_sample.head()

EPS Estimate  Reported EPS  Surprise(%)
0          1.45          1.55       0.0682
1          1.34          1.44       0.0754
2          1.07          1.17       0.0972
3          1.18          1.05      -0.1073
4          1.25          1.06      -0.1514

In [ ]:
earning_dup = pd.concat([earning_sample[:1], earning_sample]).reset_index(drop=True)
earning_dup.head()

EPS Estimate  Reported EPS  Surprise(%)
0          1.45          1.55       0.0682
1          1.45          1.55       0.0682
2          1.34          1.44       0.0754
3          1.07          1.17       0.0972
4          1.18          1.05      -0.1073

In [ ]:
# 중복 제거
earning_dup.drop_duplicates(subset=['EPS Estimate'], keep='first', inplace=True)
earning_dup.head()

EPS Estimate  Reported EPS  Surprise(%)
0          1.45          1.55       0.0682
2          1.34          1.44       0.0754
3          1.07          1.17       0.0972
4          1.18          1.05      -0.1073
5          1.25          1.06      -0.1514

In [ ]:
# 각 열의 data type
earning_sample.dtypes

EPS Estimate    float64
Reported EPS    float64
Surprise(%)     float64
dtype: object

In [ ]:
# warning 끄기
pd.options.mode.chained_assignment = None

In [ ]:
!pip install yahoo_fin > /dev/null&
import yahoo_fin.stock_info as si

price = si.get_data(ticker)
type(price)

pandas.core.frame.DataFrame

In [ ]:
price.head()

open      high       low     close  adjclose     volume ticker
2004-08-19  2.502503  2.604104  2.401401  2.511011  2.511011  893181924  GOOGL
2004-08-20  2.527778  2.729730  2.515015  2.710460  2.710460  456686856  GOOGL
2004-08-23  2.771522  2.839840  2.728979  2.737738  2.737738  365122512  GOOGL
2004-08-24  2.783784  2.792793  2.591842  2.624374  2.624374  304946748  GOOGL
2004-08-25  2.626627  2.702703  2.599600  2.652653  2.652653  183772044  GOOGL

In [ ]:
price_sort_index = price.sort_index(ascending=False) # 인덱스 기준 정렬
price_sort_index.head()

open        high         low       close    adjclose  \
2023-11-07  130.710007  131.910004  129.880005  130.970001  130.970001   
2023-11-06  129.050003  130.339996  128.669998  130.250000  130.250000   
2023-11-03  128.020004  129.529999  127.860001  129.100006  129.100006   
2023-11-02  128.419998  128.979996  126.930000  127.489998  127.489998   
2023-11-01  124.070000  126.489998  123.720001  126.449997  126.449997   

              volume ticker  
2023-11-07  29741800  GOOGL  
2023-11-06  19052700  GOOGL  
2023-11-03  26380100  GOOGL  
2023-11-02  27124600  GOOGL  
2023-11-01  30082400  GOOGL

In [ ]:
price_sort_values = price.sort_values(by='close', ascending=False) # 열 기준 정렬
price_sort_values.head()

open        high         low       close    adjclose  \
2021-11-18  148.241501  150.580505  147.884506  149.838501  149.838501   
2021-11-08  149.824997  150.615005  148.430496  149.031006  149.031006   
2021-11-19  149.975494  150.966507  148.899002  148.926498  148.926498   
2021-11-09  149.233002  149.834503  147.244995  148.918503  148.918503   
2021-11-05  149.169495  150.327499  148.197006  148.852005  148.852005   

              volume ticker  
2021-11-18  35608000  GOOGL  
2021-11-08  23052000  GOOGL  
2021-11-19  33682000  GOOGL  
2021-11-09  19530000  GOOGL  
2021-11-05  38354000  GOOGL

In [ ]:
price['month'] = price.index.map(
    lambda date: date.strftime('%Y') + '-' + date.strftime('%m') # datetime -> 문자열 타입
)
price.head()

open      high       low     close  adjclose     volume  \
2004-08-19  2.502503  2.604104  2.401401  2.511011  2.511011  893181924   
2004-08-20  2.527778  2.729730  2.515015  2.710460  2.710460  456686856   
2004-08-23  2.771522  2.839840  2.728979  2.737738  2.737738  365122512   
2004-08-24  2.783784  2.792793  2.591842  2.624374  2.624374  304946748   
2004-08-25  2.626627  2.702703  2.599600  2.652653  2.652653  183772044   

           ticker    month  
2004-08-19  GOOGL  2004-08  
2004-08-20  GOOGL  2004-08  
2004-08-23  GOOGL  2004-08  
2004-08-24  GOOGL  2004-08  
2004-08-25  GOOGL  2004-08

In [ ]:
# 그룹별 집계
price_mean = (price.groupby(by='month')[['open', 'close']]
              .agg(open_mean=('open', 'mean'),
                   close_mean=('close', 'mean'))
              .reset_index())
price_mean.head()

month  open_mean  close_mean
0  2004-08   2.637610    2.634190
1  2004-09   2.802231    2.833512
2  2004-10   3.816078    3.834608
3  2004-11   4.458601    4.441823
4  2004-12   4.539460    4.548799

In [ ]:
price_mean = (price.groupby(by='month')
              .agg({'open': 'mean', 'close': 'mean'})
              .reset_index())
price_mean.head()

month      open     close
0  2004-08  2.637610  2.634190
1  2004-09  2.802231  2.833512
2  2004-10  3.816078  3.834608
3  2004-11  4.458601  4.441823
4  2004-12  4.539460  4.548799

In [ ]:
# 열이름 변경
price_mean.rename(
    {'open': 'open_mean', 'close': 'close_mean'},
    axis=1,
    inplace=True
)
price_mean.head()

month  open_mean  close_mean
0  2004-08   2.637610    2.634190
1  2004-09   2.802231    2.833512
2  2004-10   3.816078    3.834608
3  2004-11   4.458601    4.441823
4  2004-12   4.539460    4.548799

In [ ]:
price.groupby(by='month').agg({'open': 'min', 'close': 'max'}).reset_index().head()

month      open     close
0  2004-08  2.502503  2.737738
1  2004-09  2.482232  3.280280
2  2004-10  3.273273  4.837337
3  2004-11  4.115866  4.905656
4  2004-12  4.260511  4.944945

In [ ]:
price.groupby(by='month')[['open', 'close']].mean().reset_index().head()

month      open     close
0  2004-08  2.637610  2.634190
1  2004-09  2.802231  2.833512
2  2004-10  3.816078  3.834608
3  2004-11  4.458601  4.441823
4  2004-12  4.539460  4.548799

In [ ]:
price.groupby(by='month')[['open', 'close']].mean().head() # groupby 값이 인덱스

open     close
month                      
2004-08  2.637610  2.634190
2004-09  2.802231  2.833512
2004-10  3.816078  3.834608
2004-11  4.458601  4.441823
2004-12  4.539460  4.548799

In [ ]:
# NumPy: 배열
arr = np.array([[1,2], [2,1]])
x = earning_sample[['EPS Estimate']].values
type(x)

numpy.ndarray

In [ ]:
x.shape # 행렬의 크기(행열 수)

(77, 1)

In [ ]:
x_t = x.transpose() # 전치 행렬
x_t

array([[1.45, 1.34, 1.07, 1.18, 1.25, 1.28, 1.3 , 1.37, 1.17, 0.97, 0.79,
        0.8 , 0.56, 0.41, 0.52, 0.63, 0.62, 0.56, 0.53, 0.54, 0.52, 0.48,
        0.46, 0.5 , 0.42, 0.22, 0.37, 0.48, 0.43, 0.4 , 0.4 , 0.41, 0.36,
        0.33, 0.33, 0.36, 0.33, 0.31, 0.32, 0.31, 0.26, 0.27, 0.27, 0.26,
        0.27, 0.25, 0.24, 0.26, 0.22, 0.2 , 0.2 , 0.2 , 0.17, 0.16, 0.16,
        0.16, 0.14, 0.13, 0.12, 0.12, 0.12, 0.12, 0.11, 0.11, 0.09, 0.09,
        0.08, 0.07, 0.06, 0.06, 0.05, 0.04, 0.03, 0.03, 0.02, 0.02, 0.01]])

In [ ]:
x_t.shape

(1, 77)

In [ ]:
arr2 = np.array([[1, 0], [0, 1]])

# 사칙 연산: 각 원소에 대응
arr + arr2

array([[2, 2],
       [2, 2]])

In [ ]:
arr - arr2

array([[0, 2],
       [2, 0]])

In [ ]:
arr * arr2

array([[1, 0],
       [0, 1]])

In [ ]:
arr / np.array([[2,1], [1,2]])

array([[0.5, 2. ],
       [2. , 0.5]])

In [ ]:
np.matmul(arr, arr2) # 행렬곱

array([[1, 2],
       [2, 1]])

In [ ]:
np.ones((5,1)) # 1로만 이루어진 배열(행,열)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
x = np.concatenate((np.ones((x.shape[0], 1)), x), axis=1) # 열(cf. 행: 0)
x[:2]

array([[1.  , 1.45],
       [1.  , 1.34]])

In [ ]:
x = earning_sample[['EPS Estimate', 'Reported EPS']].values
np.mean(x, axis=0) # 열(cf. 행: 1)

array([0.40584416, 0.44116883])

In [ ]:
# 검산
np.mean(x[:, 0]), np.mean(x[:, 1])

(0.4058441558441559, 0.44116883116883127)

In [ ]:
np.var(x, axis=0)

array([0.13762948, 0.16910643])

In [ ]:
# 검산
np.var(x[:, 0]), np.var(x[:, 1])

(0.13762948220610557, 0.16910642604149095)

In [ ]:
arr + 1 # broadcasting

array([[2, 3],
       [3, 2]])

In [ ]:
x_mean = np.mean(x, axis=0) # 열
x_mean.shape, x.shape

((2,), (77, 2))

In [ ]:
x_center = x - x_mean
x_center.shape

(77, 2)

In [ ]:
a = x_center/np.std(x, axis=0)
a.shape

(77, 2)

In [ ]:
u, s, v_t = np.linalg.svd(a) # 선형 대수
u, s, v_t

(array([[-0.31625327, -0.0566987 , -0.20899291, ...,  0.11757218,
          0.12070976,  0.12041339],
        [-0.28388735, -0.04277436, -0.0267729 , ...,  0.02911487,
          0.01804349,  0.03059611],
        [-0.20444372, -0.00859642,  0.96737088, ...,  0.01809536,
          0.01879802,  0.01851822],
        ...,
        [ 0.11706315,  0.01928832,  0.01868901, ...,  0.98943627,
         -0.01080353, -0.01082177],
        [ 0.11845864,  0.00761838,  0.01890701, ..., -0.01052197,
          0.98910074, -0.0107699 ],
        [ 0.1200055 ,  0.02055417,  0.01915907, ..., -0.01084025,
         -0.01107725,  0.98889435]]),
 array([12.32188849,  1.4734531 ]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [ ]:
v = v_t.transpose()
v

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [ ]:
transformed = np.matmul(a, v)
transformed[:2]

array([[-3.89683756, -0.08354288],
       [-3.49802828, -0.06302601]])

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(a)

PCA(n_components=2)

In [ ]:
pca.singular_values_

array([12.32188849,  1.4734531 ])

In [ ]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [ ]:
pca.transform(a)[:2]

array([[ 3.89683756, -0.08354288],
       [ 3.49802828, -0.06302601]])

In [ ]:
pd.DataFrame({'a': [1,2], 'b': [3,4]}).applymap(lambda x: x+1)

a  b
0  2  4
1  3  5