In [2]:
import numpy as np

# 배열
xv = np.array([1,2,3,4,5,6,7,8,9]) # []: vector
xv = np.array(range(1,10))
xv = np.arange(1,10)
xv

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
len(xv) # 행 개수

9

In [11]:
xv.size # 원소 개수

9

In [39]:
# 행렬
xm = [[1,2,3], [4,5,6], [7,8,9]]
xm = np.array([[1,2,3], [4,5,6], [7,8,9]])
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
xm = np.reshape(xv, (3,3))
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
xm.shape # 행, 열 개수

(3, 3)

In [37]:
# list의 원소로 list도 가능!
['1', [1,2]]

['1', [1, 2]]

In [41]:
# tuple: 수정 X
tpl = (1,2,3)
type(tpl)

tuple

In [45]:
# dictionary: 인덱스 접근 X
country_code = {'korea': 1, 'us': 2, 'japan': 3}
len(country_code)

3

In [47]:
country_code.keys()

dict_keys(['korea', 'us', 'japan'])

In [49]:
country_code.values()

dict_values([1, 2, 3])

In [50]:
country_code.items()

dict_items([('korea', 1), ('us', 2), ('japan', 3)])

In [51]:
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
# shallow copy: xm, xm2 같은 주소 사용.
xm = [[1,2,3], [4,5,6], [7,8,9]]
xm2 = xm
xm3 = xm.copy()
xm[0][0] = 10
xm2

[[10, 2, 3], [4, 5, 6], [7, 8, 9]]

In [92]:
xm3

[[10, 2, 3], [4, 5, 6], [7, 8, 9]]

In [95]:
xv = [1,2,3]
xv2 = xv
xv3 = xv.copy() # 일차원 배열은 별개
xv.append('added')

print(xv, xv2, xv3)

[1, 2, 3, 'added'] [1, 2, 3, 'added'] [1, 2, 3]


In [98]:
# 별 개 주소로 복사 (cf. R은 항상 deep copy)
import copy
ym = [[1,2,3], [4,5,6], [7,8,9]]
ym2 = copy.deepcopy(ym)
ym[0][0] = 10
ym2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [106]:
xm = np.array([[1,2,3], [4,5,6], [7,8,9]])
xm2 = xm
xm[0][0] = 10
print(xm)
print(xm2)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [107]:
ym = np.array([[1,2,3], [4,5,6], [7,8,9]])
ym2 = ym.copy()
ym[0][0] = 10
print(ym)
print(ym2)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
import pandas as pd

d = {'name': ['Kim', 'Lee', 'Park'], 'height': [170, 180, 175]}
df1 = pd.DataFrame(data=d)
df1

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [2]:
df2 = pd.DataFrame([['Kim', 170], ['Lee', 180], ['Park', 175]],
                   columns=['name', 'height'])
df2

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [5]:
df3 = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]),
                   columns=['a', 'b', 'c'])
df3

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
df3.describe()

a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [12]:
df1[['name', 'height']] # 열 선택

name  height
0   Kim     170
1   Lee     180
2  Park     175

In [13]:
df1.iloc[0:2]

name  height
0  Kim     170
1  Lee     180

In [18]:
df1.iloc[:, 1] # 행, 열

0    170
1    180
2    175
Name: height, dtype: int64

In [19]:
df1.iloc[:, -1]

0    170
1    180
2    175
Name: height, dtype: int64

In [20]:
df1.iloc[[1,2], 0]

1     Lee
2    Park
Name: name, dtype: object

In [23]:
# ndarray: n-dimensional array
x1 = [1,2,3,4]; x2 = [5,6,7,8]
y1 = np.array(x1); y2 = np.array(x2)

x1+[2]

[1, 2, 3, 4, 2]

In [24]:
y1+2

array([3, 4, 5, 6])

In [25]:
x1 + x2

[1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
y1 + y2

array([ 6,  8, 10, 12])

In [3]:
xrow = np.array([1,2,3]) # 행 벡터
xcol = np.array([[1],[2],[3]]) # 열 벡터
print(xrow.shape)
print(xcol.shape)

(3,)
(3, 1)


In [5]:
a = np.array(range(1,11,2))
a

array([1, 3, 5, 7, 9])

In [6]:
a1 = np.delete(a, 2)
a1

array([1, 3, 7, 9])

In [7]:
a2 = np.delete(a, [0,1,3])
a2

array([5, 9])

In [8]:
a3 = np.append(a, 11)
a3

array([ 1,  3,  5,  7,  9, 11])

In [9]:
a4 = np.insert(a, 1, 2)
a4

array([1, 2, 3, 5, 7, 9])

In [10]:
a5 = np.insert(a, 2, [1,2,3])
a5

array([1, 3, 1, 2, 3, 5, 7, 9])

In [11]:
mx1 = np.array(range(1,10)).reshape(3,3)
mx1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mx2 = np.append(mx1, np.array([10, 20, 30]).reshape(1,3), axis=0)
mx2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [13]:
mx3 = np.append(mx1, np.array([10, 20, 30]).reshape(3,1), axis=1)
mx3

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

In [14]:
mx4 = np.delete(mx1, 0, axis=0)
mx4

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
mx5 = np.delete(mx1, [0,1], axis=1)
mx5

array([[3],
       [6],
       [9]])

In [16]:
mx6 = np.insert(mx1, 1, np.array([10,20,30]), axis=0)
mx6

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
mx7 = np.insert(mx1, 1, np.array(range(10,100,10)).reshape(3,3), axis=1)
mx7

array([[ 1, 10, 40, 70,  2,  3],
       [ 4, 20, 50, 80,  5,  6],
       [ 7, 30, 60, 90,  8,  9]])

In [18]:
mx1 = np.array(range(1,7)).reshape(2,3)
mx1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
mx2 = np.hstack((np.repeat(1,3).reshape(3,1),
                np.repeat(2,3).reshape(3,1)))
mx2


array([[1, 2],
       [1, 2],
       [1, 2]])

In [20]:
mx3 = np.matmul(mx1, mx2)
mx3

array([[ 6, 12],
       [15, 30]])

In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])